export const jobApplicationCopy = {
  loadingRole: "Loading role…",
  roleUnavailable: "This role is no longer accepting applications.",
  jobsUnavailable: "Current openings could not be refreshed. Please try again shortly.",
  applyNote: "Opens SATCO's secure application form.",
  detailEyebrow: "Careers at SATCO",
  overviewEyebrow: "Job overview",
  cardHeading: "Apply for this role",
  departmentLabel: "Department",
  sectorLabel: "Sector",
  levelLabel: "Level",
  experienceRequiredLabel: "Experience required",
  educationLabel: "Education",
  applicationDeadlineLabel: "Application deadline",
  eyebrow: "Careers application",
  titlePrefix: "Apply for",
  lead: "Complete the form below and your application will be sent directly to the SATCO recruitment team.",
  formHeading: "Applicant information",
  requiredNote: "* Required field",
  fullNameLabel: "Full name",
  emailLabel: "Email address",
  phoneLabel: "Phone number",
  currentCityLabel: "Current city",
  countryLabel: "Country of residence",
  currentJobTitleLabel: "Current job title",
  yearsExperienceLabel: "Years of experience",
  qualificationLabel: "Highest qualification",
  specializationLabel: "Major / specialization",
  employerLabel: "Current employer",
  linkedinLabel: "LinkedIn profile",
  noticePeriodLabel: "Availability / notice period",
  skillsLabel: "Key skills",
  skillsHint: "Optional — separate skills with commas.",
  cvLabel: "CV / résumé",
  cvHint: "PDF, DOC, or DOCX — maximum 5 MB.",
  coverNoteLabel: "Cover note",
  coverNoteHint: "Briefly describe the experience most relevant to this role.",
  screeningHeading: "Role-specific questions",
  privacyLabel: "I confirm that I have read and accept the recruitment privacy notice.",
  submitLabel: "Submit application",
  submittingLabel: "Submitting…",
  successHeading: "Application received",
  successMessage: "Thank you. Your application has been sent to the SATCO recruitment team.",
  errorMessage: "We could not submit your application. Please try again.",
  backToRole: "Back to role details",
  roleSummaryHeading: "Role",
  locationLabel: "Location",
} as const;
